# Generated by Django 2.0.3 on 2019-02-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('signed_up', models.DateTimeField()),
                ('location', models.TextField()),
                ('twitch_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('date', models.DateField()),
                ('emulated', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Category')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_run_set', to='stats.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
    ]
