# Generated by Django 2.0.3 on 2019-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
