# Generated by Django 2.0.3 on 2019-02-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Category'),
        ),
    ]
