# Generated by Django 2.0.3 on 2019-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190208_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='first_run_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
