# Generated by Django 2.0.3 on 2019-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_run_first_run_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='first_run_by_user',
            new_name='first_run_by_player',
        ),
    ]
