# Generated by Django 2.0.3 on 2019-02-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_run_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='first_run_by_player',
        ),
    ]
