# Generated by Django 2.0.3 on 2019-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='signed_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
