# Generated by Django 2.0.3 on 2019-04-03 09:56

import django.contrib.auth.validators
from django.db import migrations, models
import server.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20180418_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(error_messages={'unique': 'A player with that username already exists.'}, max_length=150, unique=True, validators=[server.core.validators.UnicodeUsernameValidator(), django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Username'),
        ),
    ]
