# Generated by Django 2.0.3 on 2018-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_datamigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtime',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
