# Generated by Django 2.0.3 on 2018-04-18 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtime_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtime',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtime',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomtime',
            name='media',
            field=models.FileField(blank=True, upload_to='roomtimes/'),
        ),
    ]
