# Generated by Django 2.0.3 on 2018-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20180418_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtime',
            name='lttphack_version',
            field=models.IntegerField(choices=[(7, 'V7'), (8, 'V8'), (9, 'V9')], default=9),
        ),
        migrations.AlterField(
            model_name='roomtime',
            name='idle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
