# Generated by Django 2.0.3 on 2018-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomtime_twitch_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtime',
            name='lag',
            field=models.IntegerField(),
        ),
    ]
