# Generated by Django 2.0.3 on 2018-05-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20180425_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['segment__sort', 'sort']},
        ),
    ]
